// Auto-generated. Do not edit!

// (in-package nav2d_navigator.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class LocalizeGoal {
  constructor() {
    this.velocity = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type LocalizeGoal
    // Serialize message field [velocity]
    bufferInfo = _serializer.float32(obj.velocity, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type LocalizeGoal
    let tmp;
    let len;
    let data = new LocalizeGoal();
    // Deserialize message field [velocity]
    tmp = _deserializer.float32(buffer);
    data.velocity = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'nav2d_navigator/LocalizeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e4ff88b32504f688719a85e0753f63ce';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 velocity
    
    `;
  }

};

module.exports = LocalizeGoal;
