// Auto-generated. Do not edit!

// (in-package nav2d_navigator.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MoveToPosition2DResult {
  constructor() {
    this.final_pose = new geometry_msgs.msg.Pose2D();
    this.final_distance = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type MoveToPosition2DResult
    // Serialize message field [final_pose]
    bufferInfo = geometry_msgs.msg.Pose2D.serialize(obj.final_pose, bufferInfo);
    // Serialize message field [final_distance]
    bufferInfo = _serializer.float32(obj.final_distance, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type MoveToPosition2DResult
    let tmp;
    let len;
    let data = new MoveToPosition2DResult();
    // Deserialize message field [final_pose]
    tmp = geometry_msgs.msg.Pose2D.deserialize(buffer);
    data.final_pose = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [final_distance]
    tmp = _deserializer.float32(buffer);
    data.final_distance = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'nav2d_navigator/MoveToPosition2DResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1494b1c9041b641e97cee161a63a1b7b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/Pose2D final_pose
    float32 final_distance
    
    ================================================================================
    MSG: geometry_msgs/Pose2D
    # This expresses a position and orientation on a 2D manifold.
    
    float64 x
    float64 y
    float64 theta
    `;
  }

};

module.exports = MoveToPosition2DResult;
