// Auto-generated. Do not edit!

// (in-package nav2d_navigator.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let std_msgs = _finder('std_msgs');
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MoveToPosition2DGoal {
  constructor() {
    this.header = new std_msgs.msg.Header();
    this.target_pose = new geometry_msgs.msg.Pose2D();
    this.target_distance = 0.0;
    this.target_angle = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type MoveToPosition2DGoal
    // Serialize message field [header]
    bufferInfo = std_msgs.msg.Header.serialize(obj.header, bufferInfo);
    // Serialize message field [target_pose]
    bufferInfo = geometry_msgs.msg.Pose2D.serialize(obj.target_pose, bufferInfo);
    // Serialize message field [target_distance]
    bufferInfo = _serializer.float32(obj.target_distance, bufferInfo);
    // Serialize message field [target_angle]
    bufferInfo = _serializer.float32(obj.target_angle, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type MoveToPosition2DGoal
    let tmp;
    let len;
    let data = new MoveToPosition2DGoal();
    // Deserialize message field [header]
    tmp = std_msgs.msg.Header.deserialize(buffer);
    data.header = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [target_pose]
    tmp = geometry_msgs.msg.Pose2D.deserialize(buffer);
    data.target_pose = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [target_distance]
    tmp = _deserializer.float32(buffer);
    data.target_distance = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [target_angle]
    tmp = _deserializer.float32(buffer);
    data.target_angle = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'nav2d_navigator/MoveToPosition2DGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '471d15abce131270d05238fa2475ae64';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    std_msgs/Header header
    geometry_msgs/Pose2D target_pose
    float32 target_distance
    float32 target_angle
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose2D
    # This expresses a position and orientation on a 2D manifold.
    
    float64 x
    float64 y
    float64 theta
    `;
  }

};

module.exports = MoveToPosition2DGoal;
